# Use PHP 7.3 by replacing "php72" below with "php73"
runtime: php55

# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
#
# entrypoint: serve index.php

handlers:
- url: /.*
  script: index.php
  secure: always
  redirect_http_response_code: 301